Repository ConnectCo/ConnectCo-Server, pull requests merged in 2024-06, with the labels that each got.

#25 [REFACTOR] Entity 기본 세팅 수정
  src/main/java/com/connectCo/domain/Member/controller/MemberController.java
  src/main/java/com/connectCo/domain/Member/dto/response/MemberInfoResponse.java
  src/main/java/com/connectCo/domain/Member/dto/response/MemberLoginResponse.java
  src/main/java/com/connectCo/domain/Member/entity/Member.java
  src/main/java/com/connectCo/domain/Member/mapper/MemberMapper.java
  src/main/java/com/connectCo/domain/Member/repository/MemberRepository.java
  src/main/java/com/connectCo/domain/Member/service/AuthService.java
  src/main/java/com/connectCo/domain/Member/service/AuthServiceImpl.java
  src/main/java/com/connectCo/domain/Member/service/MemberService.java
  src/main/java/com/connectCo/domain/Member/service/MemberServiceImpl.java
  src/main/java/com/connectCo/domain/coupon/dto/response/CouponSummaryInquiryResponse.java
  src/main/java/com/connectCo/domain/coupon/entity/Coupon.java
  src/main/java/com/connectCo/domain/coupon/entity/CouponImage.java
  src/main/java/com/connectCo/domain/coupon/entity/CouponLike.java
  src/main/java/com/connectCo/domain/coupon/entity/CouponSponsorship.java
  src/main/java/com/connectCo/domain/coupon/repository/CouponLikeRepository.java
  src/main/java/com/connectCo/domain/coupon/repository/CouponRepository.java
  src/main/java/com/connectCo/domain/event/controller/EventController.java
  src/main/java/com/connectCo/domain/event/dto/response/EventDetailInquiryResponse.java
  src/main/java/com/connectCo/domain/event/dto/response/EventIdResponse.java
  src/main/java/com/connectCo/domain/event/dto/response/EventLikeResponse.java
  src/main/java/com/connectCo/domain/event/dto/response/EventSummaryInquiryResponse.java
  src/main/java/com/connectCo/domain/event/entity/Event.java
  src/main/java/com/connectCo/domain/event/entity/EventImage.java
  src/main/java/com/connectCo/domain/event/entity/EventLike.java
  src/main/java/com/connectCo/domain/event/entity/EventSponsorship.java
  src/main/java/com/connectCo/domain/event/repository/EventImageRepository.java
  src/main/java/com/connectCo/domain/event/repository/EventLikeRepository.java
  src/main/java/com/connectCo/domain/event/repository/EventRepository.java
  src/main/java/com/connectCo/domain/event/service/EventService.java
  src/main/java/com/connectCo/domain/event/service/EventServiceImpl.java
  src/main/java/com/connectCo/domain/organization/entity/Organization.java
  src/main/java/com/connectCo/domain/sponsorship/entity/Sponsor.java
  src/main/java/com/connectCo/domain/sponsorship/entity/Sponsorship.java
  src/main/java/com/connectCo/domain/store/controller/StoreController.java
  src/main/java/com/connectCo/domain/store/dto/response/StoreIdResponse.java
  src/main/java/com/connectCo/domain/store/dto/response/StoreSummaryInquiryResponse.java
  src/main/java/com/connectCo/domain/store/entity/Store.java
  src/main/java/com/connectCo/domain/store/entity/StoreImage.java
  src/main/java/com/connectCo/domain/store/entity/StoreLike.java
  src/main/java/com/connectCo/domain/store/mapper/StoreMapper.java
  src/main/java/com/connectCo/domain/store/repository/StoreImageRepository.java
  src/main/java/com/connectCo/domain/store/repository/StoreLikeRepository.java
  src/main/java/com/connectCo/domain/store/repository/StoreRepository.java
  src/main/java/com/connectCo/domain/store/service/StoreService.java
  src/main/java/com/connectCo/domain/store/service/StoreServiceImpl.java
  src/main/java/com/connectCo/domain/test/dto/request/TestRequest.java
  src/main/java/com/connectCo/global/common/BaseEntity.java
  src/main/java/com/connectCo/global/exception/CustomRestControllerAdvice.java
Labels: REFACTORING

#26 [FEAT] 쿠폰 조회하기(최신순,추천,상세) API 구현
  src/main/java/com/connectCo/domain/coupon/controller/CouponController.java
  src/main/java/com/connectCo/domain/coupon/dto/request/CouponCreateRequest.java
  src/main/java/com/connectCo/domain/coupon/dto/response/CouponIdResponse.java
  src/main/java/com/connectCo/domain/coupon/entity/Coupon.java
  src/main/java/com/connectCo/domain/coupon/mapper/CouponMapper.java
  src/main/java/com/connectCo/domain/coupon/repository/CouponImageRepository.java
  src/main/java/com/connectCo/domain/coupon/repository/CouponRepository.java
  src/main/java/com/connectCo/domain/coupon/service/CouponService.java
  src/main/java/com/connectCo/domain/coupon/service/CouponServiceImpl.java
  src/main/java/com/connectCo/domain/coupon/service/CouponeServiceImpl.java
  src/main/java/com/connectCo/domain/store/service/StoreService.java
  src/main/java/com/connectCo/domain/store/service/StoreServiceImpl.java
Labels: FEAT

#33 [FEAT] organization api 구현
  src/main/java/com/connectCo/domain/coupon/entity/Coupon.java
  src/main/java/com/connectCo/domain/coupon/repository/CouponImageRepository.java
  src/main/java/com/connectCo/domain/coupon/service/CouponService.java
  src/main/java/com/connectCo/domain/coupon/service/CouponServiceImpl.java
  src/main/java/com/connectCo/domain/organization/controller/OrganizationController.java
  src/main/java/com/connectCo/domain/organization/dto/request/OrganizationCreateRequest.java
  src/main/java/com/connectCo/domain/organization/dto/request/OrganizationUpdateRequest.java
  src/main/java/com/connectCo/domain/organization/dto/response/OrganizationIdResponse.java
  src/main/java/com/connectCo/domain/organization/dto/response/OrganizationInquiryResponse.java
  src/main/java/com/connectCo/domain/organization/dto/response/OrganizationSearchResponse.java
  src/main/java/com/connectCo/domain/organization/entity/Organization.java
  src/main/java/com/connectCo/domain/organization/mapper/OrganizationMapper.java
  src/main/java/com/connectCo/domain/organization/repository/OrganizationRepository.java
  src/main/java/com/connectCo/domain/organization/service/OrganizationService.java
  src/main/java/com/connectCo/domain/organization/service/OrganizationServiceImpl.java
  src/main/java/com/connectCo/domain/search/entity/Search.java
  src/main/java/com/connectCo/global/common/dto/AddressRequest.java
  src/main/java/com/connectCo/global/exception/ErrorCode.java
  src/main/java/com/connectCo/global/validation/annotation/ExistOrganization.java
  src/main/java/com/connectCo/global/validation/validator/OrganizationExistValidator.java
Labels: FEAT

#40 [REFACTOR] store-api
  src/main/java/com/connectCo/domain/store/controller/StoreController.java
  src/main/java/com/connectCo/domain/store/dto/request/StoreCreateRequest.java
  src/main/java/com/connectCo/domain/store/dto/request/StoreUpdateRequest.java
  src/main/java/com/connectCo/domain/store/dto/response/StoreDetailInquiryResponse.java
  src/main/java/com/connectCo/domain/store/dto/response/StoreIdResponse.java
  src/main/java/com/connectCo/domain/store/dto/response/StoreLocationInquiryResponse.java
  src/main/java/com/connectCo/domain/store/dto/response/StorePagingResponse.java
  src/main/java/com/connectCo/domain/store/dto/response/StoreSummaryInquiryResponse.java
  src/main/java/com/connectCo/domain/store/mapper/StoreMapper.java
  src/main/java/com/connectCo/domain/store/repository/StoreLikeRepository.java
  src/main/java/com/connectCo/domain/store/repository/StoreRepository.java
  src/main/java/com/connectCo/domain/store/service/StoreService.java
  src/main/java/com/connectCo/domain/store/service/StoreServiceImpl.java
  src/main/java/com/connectCo/global/common/dto/AddressResponse.java
  src/main/java/com/connectCo/global/common/mapper/CommonMapper.java
Labels: REFACTORING, FIX
