Repository ConnectCo/ConnectCo-Server, pull requests merged in 2025-03, with the labels that each got.

#76 [FIX] 일부 오류 해결 및 쿠폰 조회 API 구햔
  src/main/java/com/connectCo/config/security/SecurityConstant.java
  src/main/java/com/connectCo/domain/coupon/controller/CouponController.java
  src/main/java/com/connectCo/domain/coupon/dto/response/CouponDetailInquiryResponse.java
  src/main/java/com/connectCo/domain/coupon/dto/response/CouponSummaryInquiryResponse.java
  src/main/java/com/connectCo/domain/coupon/entity/CouponSearchType.java
  src/main/java/com/connectCo/domain/coupon/entity/CouponType.java
  src/main/java/com/connectCo/domain/coupon/mapper/CouponMapper.java
  src/main/java/com/connectCo/domain/coupon/repository/CouponRepository.java
  src/main/java/com/connectCo/domain/coupon/service/CouponService.java
  src/main/java/com/connectCo/domain/coupon/service/CouponServiceImpl.java
  src/main/java/com/connectCo/domain/event/dto/response/EventDetailInquiryResponse.java
  src/main/java/com/connectCo/domain/event/dto/response/EventSummaryInquiryResponse.java
  src/main/java/com/connectCo/domain/event/mapper/EventMapper.java
  src/main/java/com/connectCo/domain/member/client/GoogleMemberClient.java
  src/main/java/com/connectCo/domain/member/client/KakaoMemberClient.java
  src/main/java/com/connectCo/domain/member/client/NaverMemberClient.java
  src/main/java/com/connectCo/domain/member/controller/AuthController.java
  src/main/java/com/connectCo/domain/organization/mapper/OrganizationMapper.java
  src/main/java/com/connectCo/global/exception/ErrorCode.java
  src/main/java/com/connectCo/global/validation/ParamValidator.java
Labels: FEAT, FIX

#77 fix: 구글 로그인 방식 수정
  build.gradle
  src/main/java/com/connectCo/domain/member/client/GoogleMemberClient.java
  src/main/java/com/connectCo/domain/member/service/AuthServiceImpl.java
Labels: FIX

#78 feat: 로그인 API 완료
  build.gradle
  src/main/java/com/connectCo/domain/member/client/AppleMemberClient.java
  src/main/java/com/connectCo/domain/member/client/GoogleMemberClient.java
  src/main/java/com/connectCo/domain/member/client/KakaoMemberClient.java
  src/main/java/com/connectCo/domain/member/dto/client/GoogleMemberResponse.java
  src/main/java/com/connectCo/domain/member/service/AuthServiceImpl.java
  src/main/java/com/connectCo/global/exception/ErrorCode.java
Labels: FEAT

#82 [FEAT] 검색 API 구현
  src/main/java/com/connectCo/config/security/SecurityConstant.java
  src/main/java/com/connectCo/domain/coupon/controller/CouponController.java
  src/main/java/com/connectCo/domain/coupon/repository/CouponRepository.java
  src/main/java/com/connectCo/domain/coupon/service/CouponService.java
  src/main/java/com/connectCo/domain/coupon/service/CouponServiceImpl.java
  src/main/java/com/connectCo/domain/event/controller/EventController.java
  src/main/java/com/connectCo/domain/event/entity/EventSearchType.java
  src/main/java/com/connectCo/domain/event/repository/EventRepository.java
  src/main/java/com/connectCo/domain/event/service/EventService.java
  src/main/java/com/connectCo/domain/event/service/EventServiceImpl.java
Labels: FEAT

#85 [FIX] 이벤트, 쿠폰 조회 API 수정
  src/main/java/com/connectCo/config/security/SecurityConstant.java
  src/main/java/com/connectCo/domain/coupon/controller/CouponController.java
  src/main/java/com/connectCo/domain/coupon/dto/response/CouponSummaryInquiryResponse.java
  src/main/java/com/connectCo/domain/coupon/mapper/CouponMapper.java
  src/main/java/com/connectCo/domain/event/controller/EventController.java
  src/main/java/com/connectCo/domain/event/dto/response/EventLocationInquiryResponse.java
  src/main/java/com/connectCo/domain/event/dto/response/EventSummaryInquiryResponse.java
  src/main/java/com/connectCo/domain/event/mapper/EventMapper.java
Labels: FIX

#84 [FEAT] 협찬 및 위치 엔티티 추가
  src/main/java/com/connectCo/domain/location/entity/Location.java
  src/main/java/com/connectCo/domain/sponsorship/entity/Sponsor.java
  src/main/java/com/connectCo/domain/sponsorship/entity/Sponsorship.java
  src/main/java/com/connectCo/domain/sponsorship/entity/SponsorshipStatus.java
  src/main/java/com/connectCo/global/exception/ErrorCode.java
Labels: FEAT
